In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

# Here, our model consists of a sequence of two Dense layers, which are densely connected (also called fully connected) neutral layers.
# The second layers ia a 10-way softmax classification layer, which means it will return an array of 10 probability scores.
# Each score will be the probability that the current digit image belongs to one of our 10 digit classes

In [9]:
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [11]:
# Will iterate on the training data in mini-batches of 128 samples,
# 5 times over (each iteration is called an epoch). For each batch,
# the model will compute the gradient of the loss with regard to
# the weighs (using backprop) and move the weights in the direction
# that will reduce the value of the loss.
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 1s 2ms/step - loss: 0.2543 - accuracy: 0.9269
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1043 - accuracy: 0.9687
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0691 - accuracy: 0.9793
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0498 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0369 - accuracy: 0.9891


In [12]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 32ms/step


array([4.4905821e-08, 7.8907603e-10, 2.9133212e-06, 5.3797185e-04,
       7.0147408e-12, 3.7968725e-08, 1.3203064e-14, 9.9945551e-01,
       1.6810841e-07, 3.3816459e-06], dtype=float32)

In [13]:
predictions[0].argmax()

7

In [14]:
predictions[0][7]

0.9994555

In [15]:
test_labels[0]

7