In [1]:
import tensorflow as tf

x = tf.ones(shape=(2, 1)) # same as np.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [2]:
x = tf.zeros(shape=(2, 1)) # same as np.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [3]:
# Tensor of random values drawn from a normal distrubution with mean 0 and standard deviation 1.
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.0)
print(x)

tf.Tensor(
[[0.433218]
 [0.812614]
 [1.712028]], shape=(3, 1), dtype=float32)


In [4]:
# Tensor of random values drawn from a uniform distrubution between 0 and 1
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.0)
print(x)

tf.Tensor(
[[0.38777494]
 [0.02667654]
 [0.5604969 ]], shape=(3, 1), dtype=float32)


In [5]:
# The biggest difference between NumPy arrays and TensorFlow tensors is
# that TensorFlow tensors aren't assignable: they're constant.
# For instance, in NumPy you can do the following:
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0

In [6]:
# Try to do the same thing in TensorFlow, and you will get an error
x = tf.ones(shape=(2, 2))
x[0, 0] = 0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

In [ ]:
# the state can be modified via its `assign` method as follows
v.assign(tf.ones((3, 1)))

In [ ]:
v[0, 0].assign(3.)

In [ ]:
v.assign_add(tf.ones((3, 1)))

In [ ]:
a = tf.ones((2, 2))
b = tf.square(a) # take the square
c = tf.sqrt(a) # take the square root
d = b + c # Add two tensors
e = tf.matmul(a, b) # Take the product of two tensors
e *= d # multiply two tensors

In [9]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [11]:
# with non-variables
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)
