In [18]:
import tensorflow as tf

x = tf.Variable(0.0) # instantiate a scalar Variable with an initial value of 0.
with tf.GradientTape() as tape: # Open a GradientTape scope
    y = 2 * x + 3 # Inside the scope, apply some tensor operations to our variable
grad_of_y_wrt_x = tape.gradient(y, x) # Use the tape to retrieve the gradient of the output y with respect to our variable x.
print(grad_of_y_wrt_x)
print(y)

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)


In [14]:
x = tf.Variable(tf.random.uniform((2, 2))) # Instantiate a Variable with shape (2, 2) and an initial value of all zeros.
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x) # grad_of_y_wrt_x is a tensor shape (2, 2) (like x) describing the curvature of y = 2 * a around x
print(grad_of_y_wrt_x)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)


In [20]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b # matmul is a "dot product" in tf

grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b]) # list of 2 tensors with the same shapes as W and b
print(grad_of_y_wrt_W_and_b)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2192291, 1.2192291],
       [1.2551122, 1.2551122]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]
